version: "3.8"

services:
  app:
    container_name: Sistema-Gerenciador-Ouvidoria
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  database:
    container_name: ouvidoria-mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: wyz*Hee@1102
      MYSQL_DATABASE: ouvidoria1javaavancado
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local